# coding: utf-8

"""
    API v1.0.1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pipeline_publisher_python
from pipeline_publisher_python.models.inline_response_200_messages_received import (
    InlineResponse200MessagesReceived
)  # noqa: E501
from pipeline_publisher_python.rest import ApiException


class TestInlineResponse200MessagesReceived(unittest.TestCase):
    """InlineResponse200MessagesReceived unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200MessagesReceived(self):
        """Test InlineResponse200MessagesReceived"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pipeline_publisher_python.models.inline_response_200_messages_received.InlineResponse200MessagesReceived()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
