# coding: utf-8

"""
    API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pipeline_publisher_python
from pipeline_publisher_python.api.messages_api import MessagesApi  # noqa: E501
from pipeline_publisher_python.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = pipeline_publisher_python.api.messages_api.MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_messages_post(self):
        """Test case for messages_post

        Creates a message on the pipeline  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
