# coding: utf-8

"""
    API v1.0.1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pipeline_publisher_python
from pipeline_publisher_python.models.inline_response_200 import InlineResponse200  # noqa: E501
from pipeline_publisher_python.rest import ApiException


class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pipeline_publisher_python.models.inline_response_200.InlineResponse200()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
