# coding: utf-8

"""
    API v1.0.1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pipeline_publisher_python
from pipeline_publisher_python.api.stream_metrics_api import StreamMetricsApi  # noqa: E501
from pipeline_publisher_python.rest import ApiException


class TestStreamMetricsApi(unittest.TestCase):
    """StreamMetricsApi unit test stubs"""

    def setUp(self):
        self.api = pipeline_publisher_python.api.stream_metrics_api.StreamMetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stream_metrics_get(self):
        """Test case for stream_metrics_get

        Fetches metrics about the stream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
