# coding: utf-8

"""
    API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'noun': 'str',
        'meta': 'object',
        'identifiers': 'object',
        'data': 'object'
    }

    attribute_map = {
        'noun': 'noun',
        'meta': 'meta',
        'identifiers': 'identifiers',
        'data': 'data'
    }

    def __init__(self, noun=None, meta=None, identifiers=None, data=None):  # noqa: E501
        """Message - a model defined in Swagger"""  # noqa: E501

        self._noun = None
        self._meta = None
        self._identifiers = None
        self._data = None
        self.discriminator = None

        self.noun = noun
        if meta is not None:
            self.meta = meta
        self.identifiers = identifiers
        if data is not None:
            self.data = data

    @property
    def noun(self):
        """Gets the noun of this Message.  # noqa: E501


        :return: The noun of this Message.  # noqa: E501
        :rtype: str
        """
        return self._noun

    @noun.setter
    def noun(self, noun):
        """Sets the noun of this Message.


        :param noun: The noun of this Message.  # noqa: E501
        :type: str
        """
        if noun is None:
            raise ValueError("Invalid value for `noun`, must not be `None`")  # noqa: E501

        self._noun = noun

    @property
    def meta(self):
        """Gets the meta of this Message.  # noqa: E501


        :return: The meta of this Message.  # noqa: E501
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this Message.


        :param meta: The meta of this Message.  # noqa: E501
        :type: object
        """

        self._meta = meta

    @property
    def identifiers(self):
        """Gets the identifiers of this Message.  # noqa: E501


        :return: The identifiers of this Message.  # noqa: E501
        :rtype: object
        """
        return self._identifiers

    @identifiers.setter
    def identifiers(self, identifiers):
        """Sets the identifiers of this Message.


        :param identifiers: The identifiers of this Message.  # noqa: E501
        :type: object
        """
        if identifiers is None:
            raise ValueError("Invalid value for `identifiers`, must not be `None`")  # noqa: E501

        self._identifiers = identifiers

    @property
    def data(self):
        """Gets the data of this Message.  # noqa: E501


        :return: The data of this Message.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Message.


        :param data: The data of this Message.  # noqa: E501
        :type: object
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
